spring:
  application:
    name: Lab2

  datasource:

    url: jdbc:postgresql://localhost:5432/employeedb
    username: USER_NAME
    password: USER_PASSWORD

    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

jwt:
  secret: SECRET_KEY
  expiration: 3600000

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG

server:
  port: 8988


  git add .
git commit -m "Lab 4: Swagger API documentation"
  git push -u origin lab4-swagger
  git add .
git commit -m "Lab 4: Swagger API documentation"
  git push -u origin lab4-swagger
